name: medicine_reminder
description: A new Flutter project.


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  
  flutter:
    sdk: flutter
  


  cupertino_icons: ^1.0.2
  sizer: ^3.1.3
  google_fonts: ^6.3.2
  flutter_svg:
  rxdart:
  provider:
  shared_preferences:
  flare_flutter:  ^3.0.2
  flutter_local_notifications: ^19.4.2
  permission_handler: ^12.0.1
  http: ^1.2.2
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  flutter_easyloading: ^3.0.5
  cloud_firestore: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4  

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/pill.png"


  flutter_lints: ^2.0.0



flutter:


  uses-material-design: true


  assets:
    - assets/icons/
    - assets/animations/
    - assets/sound/
